import type {
  StatementGeneratedBy,
  StatementRowSummary,
} from "../types/statement-list.types"
import type { PortfolioResponseDTO } from "@/services/portfolio/dto/portfolio-response.dto"
import type { StatementResponseDTO } from "@/services/statement/dto/statement-response.dto"
import type { UserResponseDTO } from "@/services/user/dto/user-response.dto"

/**
 * @summary
 * Composes the derived data of the statement rows.
 *
 * @remarks
 * Resolves the portfolio acronym and name per statement and
 * attaches the signed-in user as the generator whenever the
 * row was generated by that user. Summaries are keyed by
 * statement id.
 *
 * @explanation
 * Use this helper in the page loader to build the summary
 * record consumed by the datatable and the delete dialog.
 *
 * @param statements - The statement rows.
 * @param portfolios - The session portfolios for lookups.
 * @param userId - The id of the signed-in user.
 * @param user - The display data of the signed-in user.
 *
 * @returns The summaries keyed by statement id.
 *
 * @example
 * const SUMMARIES = BuildStatementRowSummaries(
 *   STATEMENTS,
 *   PORTFOLIOS,
 *   "user-1",
 *   USER
 * );
 *
 * @author Moisés Reis
 *
 * @date 2026-09-25
 */
export function BuildStatementRowSummaries(
  statements: StatementResponseDTO[],
  portfolios: PortfolioResponseDTO[],
  userId: string,
  user: UserResponseDTO
): Record<string, StatementRowSummary> {
  const PORTFOLIOS_BY_ID = new Map(
    portfolios.map((portfolio) => [portfolio.id, portfolio])
  )

  const GENERATED_BY: StatementGeneratedBy = {
    firstName: user.firstName,
    lastName: user.lastName,
    image: user.image,
  }

  return Object.fromEntries(
    statements.map((statement) => {
      const PORTFOLIO = statement.portfolioId
        ? PORTFOLIOS_BY_ID.get(statement.portfolioId)
        : undefined

      return [
        statement.id,
        {
          portfolioAcronym: PORTFOLIO?.acronym ?? "-",
          portfolioName: PORTFOLIO?.name ?? "-",
          generatedBy:
            statement.generatedByUserId === userId
              ? GENERATED_BY
              : null,
        },
      ]
    })
  )
}
