import { afterAll, beforeEach, describe, expect, it } from "vitest";

import {
  FRESH_STATEMENT,
  newStatementRepository,
  OTHER_STATEMENT,
  STATEMENT,
  STATEMENT_ID,
  seedStatementParents,
  seedStatements,
  THIRD_STATEMENT,
  THIRD_STATEMENT_ID,
  UPDATED_STATEMENT,
} from "@/__tests__/__helpers__/repositories/_report.test.helper";
import {
  OTHER_PORTFOLIO_ID,
  PORTFOLIO_ID,
} from "@/__tests__/__seeds__/_portfolio.seed";
import { OTHER_USER_ID, USER_ID } from "@/__tests__/__seeds__/_user.seed";
import {
  closeDatabase,
  resetDatabase,
} from "@/__tests__/__setup__/_database.setup";

describe("StatementRepository", () => {
  beforeEach(async () => {
    await resetDatabase();
  });

  afterAll(async () => {
    await closeDatabase();
  });

  describe("findById", () => {
    it("returns the persisted statement", async () => {
      await seedStatements();

      const FOUND = await newStatementRepository().findById(STATEMENT_ID);

      expect(FOUND?.equals(STATEMENT)).toBe(true);
    });

    it("returns null when the statement does not exist", async () => {
      expect(await newStatementRepository().findById(STATEMENT_ID)).toBeNull();
    });
  });

  describe("findAllByPortfolioId", () => {
    it("returns every statement of the portfolio", async () => {
      await seedStatements();

      const FOUND =
        await newStatementRepository().findAllByPortfolioId(PORTFOLIO_ID);

      expect(FOUND).toHaveLength(2);
      expect(FOUND.some((ROW) => ROW.equals(STATEMENT))).toBe(true);
      expect(FOUND.some((ROW) => ROW.equals(THIRD_STATEMENT))).toBe(true);
      expect(FOUND.some((ROW) => ROW.equals(OTHER_STATEMENT))).toBe(false);
    });

    it("returns an empty array when the portfolio has no statements", async () => {
      expect(
        await newStatementRepository().findAllByPortfolioId(OTHER_PORTFOLIO_ID),
      ).toEqual([]);
    });
  });

  describe("findAllByPortfolioIds", () => {
    it("returns every statement of the provided portfolios", async () => {
      await seedStatements();

      const FOUND = await newStatementRepository().findAllByPortfolioIds([
        PORTFOLIO_ID,
        OTHER_PORTFOLIO_ID,
      ]);

      expect(FOUND).toHaveLength(3);
      expect(FOUND.some((ROW) => ROW.equals(STATEMENT))).toBe(true);
      expect(FOUND.some((ROW) => ROW.equals(OTHER_STATEMENT))).toBe(true);
    });

    it("returns an empty array when no ids are provided", async () => {
      expect(await newStatementRepository().findAllByPortfolioIds([])).toEqual(
        [],
      );
    });
  });

  describe("findAllByGeneratedByUserId", () => {
    it("returns every statement generated by the user", async () => {
      await seedStatements();

      const FOUND =
        await newStatementRepository().findAllByGeneratedByUserId(USER_ID);

      expect(FOUND).toHaveLength(2);
      expect(FOUND.some((ROW) => ROW.equals(STATEMENT))).toBe(true);
      expect(FOUND.some((ROW) => ROW.equals(OTHER_STATEMENT))).toBe(true);
      expect(FOUND.some((ROW) => ROW.equals(THIRD_STATEMENT))).toBe(false);
    });

    it("returns an empty array when no statements exist", async () => {
      expect(
        await newStatementRepository().findAllByGeneratedByUserId(USER_ID),
      ).toEqual([]);
    });
  });

  describe("findAllByGeneratedByUserIds", () => {
    it("returns the statements generated by any of the provided users", async () => {
      await seedStatements();

      const FOUND = await newStatementRepository().findAllByGeneratedByUserIds([
        USER_ID,
        OTHER_USER_ID,
      ]);

      expect(FOUND).toHaveLength(3);
      expect(FOUND.some((ROW) => ROW.equals(THIRD_STATEMENT))).toBe(true);
    });

    it("returns an empty array when no ids are provided", async () => {
      expect(
        await newStatementRepository().findAllByGeneratedByUserIds([]),
      ).toEqual([]);
    });
  });

  describe("save", () => {
    it("persists a new statement", async () => {
      await seedStatementParents();

      const SAVED = await newStatementRepository().save(FRESH_STATEMENT);

      expect(SAVED.id).toBeDefined();
      expect(SAVED.fileUrl).toBe(FRESH_STATEMENT.fileUrl);
      expect(
        (await newStatementRepository().findById(SAVED.id as string))?.equals(
          SAVED,
        ),
      ).toBe(true);
    });

    it("updates an existing statement", async () => {
      await seedStatements();

      await newStatementRepository().save(UPDATED_STATEMENT);

      const FOUND = await newStatementRepository().findById(STATEMENT_ID);

      expect(FOUND?.fileUrl).toBe(UPDATED_STATEMENT.fileUrl);
      expect(FOUND?.equals(UPDATED_STATEMENT)).toBe(true);
    });
  });

  describe("delete", () => {
    it("removes the persisted statement", async () => {
      await seedStatements();

      await newStatementRepository().delete(THIRD_STATEMENT_ID);

      expect(
        await newStatementRepository().findById(STATEMENT_ID),
      ).not.toBeNull();
      expect(
        await newStatementRepository().findById(THIRD_STATEMENT_ID),
      ).toBeNull();
    });
  });
});
