import { EntityId } from "@/business/value-objects/entity-id.vo";
import type { UnitOfWorkContext } from "@/infrastructure/unit-of-work";

import type { StatementDto } from "./statement.dtos";
import { toStatementDto } from "./statement.dtos";

/**
 * Input for {@link listUserStatements}.
 */
export interface ListUserStatementsInput {
  /**
   * The id of the user who generated the statements.
   */
  userId: string;
}

/**
 * Lists the statements generated by a user.
 *
 * @param ctx - The transaction-scoped repositories.
 * @param input - The user id.
 * @returns The {@link StatementDto}s generated by the user.
 */
export async function listUserStatements(
  ctx: Pick<UnitOfWorkContext, "statements">,
  input: ListUserStatementsInput,
): Promise<StatementDto[]> {
  const statements = await ctx.statements.findAllByGeneratedByUserId(
    EntityId.create(input.userId),
  );

  return statements.map(toStatementDto);
}
