"use client"

import type { RowData } from "@tanstack/react-table"

import { EntityDatatableEditColumnsButton } from "@/presentation/parts/components/entity-datatable-edit-columns-button"
import { EntityDatatableToolbar } from "@/presentation/parts/components/entity-datatable-toolbar"
import type { EntityTable } from "@/presentation/parts/datatable/settings/entity-table-features.settings"
import { AUDIT_LOG_DATATABLE_COLUMN_LABELS } from "@/presentation/routes/audit-log/settings/labels.settings"

interface AuditLogDatatableToolbarProps<TData extends RowData> {
  table: EntityTable<TData>
  filters?: React.ReactNode
}

/**
 * @summary
 * Renders the audit log datatable toolbar.
 *
 * @remarks
 * Composes the shared datatable toolbar with the edit-columns
 * button only. Audit logs are generated by the system, so the
 * toolbar has no add-item or create action. The `filters` slot
 * renders on the left side.
 *
 * @param props - The shared table instance.
 * @param props.table - The shared table instance.
 * @param props.filters - The left-side filter group.
 *
 * @returns The audit log datatable toolbar.
 *
 * @author Moisés Reis
 *
 * @date 2026-09-25
 */
function AuditLogDatatableToolbar<TData extends RowData>({
  table,
  filters,
}: AuditLogDatatableToolbarProps<TData>) {
  return (
    <EntityDatatableToolbar
      filters={filters}
      actions={
        <EntityDatatableEditColumnsButton
          table={table}
          getColumnLabel={(column) =>
            AUDIT_LOG_DATATABLE_COLUMN_LABELS[column.id] ??
            column.id
          }
        />
      }
    />
  )
}

export { AuditLogDatatableToolbar }
