import { z } from "zod";

import { created, paginated } from "@/app/api/_core/envelope";
import { apiHandler } from "@/app/api/_core/handler";
import { slicePage } from "@/app/api/_core/pagination";
import {
  dateStringSchema,
  entityIdSchema,
  paginationQuerySchema,
} from "@/app/api/_core/schemas";
import { getPortfolio } from "@/business/use-cases/portfolio/get-portfolio.uc";
import { createStatement } from "@/business/use-cases/statement/create-statement.uc";
import { listPortfolioStatements } from "@/business/use-cases/statement/list-portfolio-statements.uc";
import { listUserStatements } from "@/business/use-cases/statement/list-user-statements.uc";

/**
 * The query parameters accepted by the statements endpoint.
 */
const STATEMENTS_QUERY = paginationQuerySchema.extend({
  portfolioId: entityIdSchema.optional(),
});

/**
 * The JSON body accepted when creating a statement.
 */
const CREATE_BODY = z
  .object({
    portfolioId: entityIdSchema.optional(),
    periodStart: dateStringSchema,
    periodEnd: dateStringSchema,
    fileUrl: z.string().trim().min(1).max(2048),
  })
  .refine((value) => value.periodStart <= value.periodEnd, {
    message: "periodStart must not be after periodEnd.",
  });

/**
 * Lists statements: those of a portfolio when `portfolioId` is provided
 * (the actor must access it), or those generated by the actor.
 */
export const GET = apiHandler({
  querySchema: STATEMENTS_QUERY,
  handler: async ({ actor, query, runtime }) => {
    const portfolioId = query.portfolioId;

    if (portfolioId !== undefined) {
      await runtime.unitOfWork.run((tx) =>
        getPortfolio(tx, {
          actorId: actor.actorId,
          portfolioId,
        }),
      );

      const statements = await runtime.unitOfWork.run((tx) =>
        listPortfolioStatements(tx, { portfolioId }),
      );
      const page = slicePage(statements, query);
      return paginated(page.items, page.meta);
    }

    const statements = await runtime.unitOfWork.run((tx) =>
      listUserStatements(tx, { userId: actor.actorId }),
    );
    const page = slicePage(statements, query);
    return paginated(page.items, page.meta);
  },
});

/**
 * Creates a statement.
 *
 * When scoped to a portfolio, the actor must have access to it.
 */
export const POST = apiHandler({
  bodySchema: CREATE_BODY,
  handler: async ({ actor, body, runtime }) => {
    const dto = await createStatement(runtime.unitOfWork, {
      actorId: actor.actorId,
      portfolioId: body.portfolioId ?? null,
      periodStart: body.periodStart,
      periodEnd: body.periodEnd,
      fileUrl: body.fileUrl,
    });
    return created(dto);
  },
});
