import type { Statement } from "@/business/entities/report/statement.entity";
import type { EntityId } from "@/business/value-objects/entity-id.vo";

/**
 * Represents the repository contract for persisting and retrieving
 * `Statement` entities.
 *
 * An `IStatement`:
 * - persists statements through {@link IStatement.save}.
 * - retrieves statements by id, portfolio id, and generating user id.
 * - removes statements by id.
 *
 * Implementations are responsible for mapping database rows to
 * `Statement` entities and back.
 */
export interface IStatement {
  /**
   * Retrieves the statement with the provided id.
   *
   * @param id - The unique identifier of the statement.
   * @returns A promise resolving to the `Statement` or `null` when
   * not found.
   */
  findById(id: EntityId): Promise<Statement | null>;

  /**
   * Retrieves all statements belonging to the provided portfolio id.
   *
   * @param portfolioId - The unique identifier of the portfolio.
   * @returns A promise resolving to the `Statement` entries or an
   * empty array when there are no matches.
   */
  findAllByPortfolioId(portfolioId: EntityId): Promise<Statement[]>;

  /**
   * Retrieves all statements generated by the provided user id.
   *
   * @param userId - The unique identifier of the user.
   * @returns A promise resolving to the `Statement` entries or an
   * empty array when there are no matches.
   */
  findAllByGeneratedByUserId(userId: EntityId): Promise<Statement[]>;

  /**
   * Persists the provided statement.
   *
   * When the statement has no id, the implementation inserts a new
   * record and the persisted `Statement` (with its generated id) is
   * returned; otherwise the existing record is updated.
   *
   * @param statement - The statement to persist.
   * @returns A promise resolving to the persisted `Statement`.
   */
  save(statement: Statement): Promise<Statement>;

  /**
   * Removes the statement with the provided id.
   *
   * @param id - The unique identifier of the statement.
   * @returns A promise that resolves when the statement is removed.
   */
  delete(id: EntityId): Promise<void>;
}
