import { ID } from "@/__tests__/__fixtures__";
import { db } from "@/__tests__/__setup__/_database.setup";
import type { Statement } from "@/business/entities";
import { Statement as StatementEntity } from "@/business/entities/report/statement.entity";
import { EntityId } from "@/business/value-objects/entity-id.vo";
import { statement } from "@/infrastructure/database/schemas";
import { seedPortfolioById } from "./_portfolio.seed";
import { seedUserById } from "./_user.seed";

/**
 * Represents a default statement fixture.
 * The statement belongs to the default portfolio. It covers
 * January 2026 and was generated by the default user.
 */
export const STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: new Date("2026-01-01T00:00:00.000Z"),
    periodEnd: new Date("2026-01-31T00:00:00.000Z"),
    fileUrl:
      "https://example.com/statements/fia-january.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.DEFAULT,
);

/**
 * Represents an alternate statement fixture.
 * The statement belongs to the other portfolio. It covers
 * February 2026 and was generated by the default user.
 */
export const OTHER_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.OTHER),
    periodStart: new Date("2026-02-01T00:00:00.000Z"),
    periodEnd: new Date("2026-02-28T00:00:00.000Z"),
    fileUrl:
      "https://example.com/statements/rf-february.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.OTHER,
);

/**
 * Represents a third statement fixture.
 * The statement belongs to the default portfolio. It covers
 * March 2026 and was generated by the other user.
 */
export const THIRD_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: new Date("2026-03-01T00:00:00.000Z"),
    periodEnd: new Date("2026-03-31T00:00:00.000Z"),
    fileUrl:
      "https://example.com/statements/fia-march.pdf",
    generatedByUserId: EntityId.create(ID.USER.OTHER),
  },
  ID.STATEMENT.THIRD,
);

/**
 * Represents an updated statement fixture.
 * The fixture uses the default statement ID but points to a
 * revised file URL with `-v2` suffix.
 */
export const UPDATED_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: STATEMENT.periodStart,
    periodEnd: STATEMENT.periodEnd,
    fileUrl:
      "https://example.com/statements/fia-january-v2.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.DEFAULT,
);

/**
 * Represents a fresh statement fixture.
 * The fixture has no persisted ID. It belongs to the default
 * portfolio and covers April 2026.
 */
export const FRESH_STATEMENT = StatementEntity.create({
  portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
  periodStart: new Date("2026-04-01T00:00:00.000Z"),
  periodEnd: new Date("2026-04-30T00:00:00.000Z"),
  fileUrl:
    "https://example.com/statements/fia-april.pdf",
  generatedByUserId: EntityId.create(ID.USER.DEFAULT),
});

/**
 * Represents the default statement identifier for test
 * fixtures.
 */
export const STATEMENT_ID = ID.STATEMENT.DEFAULT;

/**
 * Represents the alternate statement identifier for test
 * fixtures.
 */
export const OTHER_STATEMENT_ID = ID.STATEMENT.OTHER;

/**
 * Represents the third statement identifier for test
 * fixtures.
 */
export const THIRD_STATEMENT_ID = ID.STATEMENT.THIRD;

/**
 * Seeds all statement fixtures into the database.
 *
 * The function first seeds the statement parent rows. It then
 * inserts the default, alternate, and third statements.
 *
 * @returns The full array of {@link Statement} fixtures.
 */
export async function seedStatements(): Promise<Statement[]> {
  await seedStatementParents();

  for (const fixture of [
    STATEMENT,
    OTHER_STATEMENT,
    THIRD_STATEMENT,
  ]) {
    await db.insert(statement).values({
      id: fixture.id,
      portfolioId: fixture.portfolioId,
      periodStart: fixture.periodStart.toISOString(),
      periodEnd: fixture.periodEnd.toISOString(),
      fileUrl: fixture.fileUrl,
      generatedByUserId: fixture.generatedByUserId,
      createdAt: fixture.createdAt,
    });
  }

  return [STATEMENT, OTHER_STATEMENT, THIRD_STATEMENT];
}

/**
 * Seeds the parent rows required by statement fixtures.
 *
 * The function seeds the default and alternate users and the
 * default and alternate portfolios. This ensures all foreign
 * key references are satisfied before statement insertion.
 */
export async function seedStatementParents(): Promise<void> {
  await seedUserById(ID.USER.DEFAULT);
  await seedUserById(ID.USER.OTHER);
  await seedPortfolioById(ID.PORTFOLIO.DEFAULT);
  await seedPortfolioById(ID.PORTFOLIO.OTHER);
}
