"use client"

import { IconHistory } from "@tabler/icons-react"

import { EntityDatatableKpiCard } from "@/presentation/parts/components/entity-datatable-kpi-card"
import { EntityDatatableKpiGroup } from "@/presentation/parts/components/entity-datatable-kpi-group"
import { EntityEmptyTable } from "@/presentation/parts/datatable/pagination/entity-empty-table"
import type { AuditLogResponseDTO } from "@/services/audit-log/dto/audit-log-response.dto"

import { AuditLogDatatableFilters } from "../datatable/filters"
import { AuditLogDatatableTable } from "../datatable/table"
import { AuditLogDatatableToolbar } from "../datatable/toolbar"
import { useAuditLogDatatable } from "../hooks/use-audit-log-datatable.hook"
import { useAuditLogDatatableFilters } from "../hooks/use-audit-log-datatable-filters.hook"
import { useAuditLogKpis } from "../hooks/use-audit-log-kpis.hook"
import { AUDIT_LOG_EMPTY } from "../settings/labels.settings"
import type { AuditLogRowSummary } from "../types/audit-log-list.types"

interface AuditLogListProps {
  data: AuditLogResponseDTO[] | null
  summaries: Record<string, AuditLogRowSummary> | null
}

/**
 * @summary
 * Renders the audit log list screen.
 *
 * @remarks
 * Composes the KPI group, the datatable toolbar and the
 * datatable or its empty state. The screen is read-only:
 * audit logs are generated by the system and are never
 * created, edited or removed by the user.
 *
 * @param props - The list data and derived summaries.
 * @param props.data - The audit log rows.
 * @param props.summaries - Per-row derived data keyed by id.
 *
 * @returns The audit log list screen.
 *
 * @author Moisés Reis
 *
 * @date 2026-09-25
 */
function AuditLogList({ data, summaries }: AuditLogListProps) {
  const LOGS = data ?? []
  const HAS_LOGS = LOGS.length > 0

  const filters = useAuditLogDatatableFilters({
    auditLogs: LOGS,
    summaries,
  })
  const { table } = useAuditLogDatatable(
    filters.filteredAuditLogs,
    summaries
  )
  const kpis = useAuditLogKpis({ auditLogs: LOGS })

  return (
    <>
      <EntityDatatableKpiGroup>
        {kpis.map((kpi) => (
          <EntityDatatableKpiCard
            key={kpi.key}
            title={kpi.title}
            value={kpi.value}
            trend={kpi.trend}
            comparison={kpi.comparison}
            dotIndicator={kpi.dotIndicator}
            icon={kpi.icon}
          />
        ))}
      </EntityDatatableKpiGroup>

      <AuditLogDatatableToolbar
        table={table}
        filters={
          <AuditLogDatatableFilters
            query={filters.query}
            onQueryChange={filters.onQueryChange}
          />
        }
      />

      {HAS_LOGS ? (
        <AuditLogDatatableTable table={table} />
      ) : (
        <EntityEmptyTable
          icon={IconHistory}
          title={AUDIT_LOG_EMPTY.TITLE}
          description={AUDIT_LOG_EMPTY.DESCRIPTION}
        />
      )}
    </>
  )
}

export { AuditLogList }
