import { beforeEach, describe, expect, it } from "vitest";

import { ID } from "@/__tests__/__fixtures__";
import {
  OTHER_STATEMENT,
  STATEMENT,
  THIRD_STATEMENT,
} from "@/__tests__/__helpers__/interfaces/_statement.test.helper";
import { FakeUnitOfWork } from "@/__tests__/__helpers__/use-cases/_unit-of-work.test.helper";
import { listUserStatements } from "@/business/use-cases/statement/list-user-statements.uc";

describe("listUserStatements", () => {
  let unitOfWork: FakeUnitOfWork;

  beforeEach(() => {
    unitOfWork = new FakeUnitOfWork();
  });

  describe("success", () => {
    it("returns the statements generated by a user", async () => {
      unitOfWork.seed({
        statements: [STATEMENT, OTHER_STATEMENT, THIRD_STATEMENT],
      });

      const RESULT = await listUserStatements(unitOfWork as never, {
        userId: ID.USER.DEFAULT,
      });

      expect(RESULT).toHaveLength(2);
      expect(RESULT.map((s) => s.id)).toEqual([
        ID.STATEMENT.DEFAULT,
        ID.STATEMENT.OTHER,
      ]);
    });

    it("returns an empty array when the user generated no statements", async () => {
      unitOfWork.seed({ statements: [THIRD_STATEMENT] });

      const RESULT = await listUserStatements(unitOfWork as never, {
        userId: ID.USER.DEFAULT,
      });

      expect(RESULT).toEqual([]);
    });
  });
});
