import type { Statement } from "@domain/statement/entities/statement.entity"
import type { EntityId } from "@/value-objects"

/**
 * @summary
 * Defines the repository contract for `Statement` entities.
 *
 * @remarks
 * An `IStatement` persists, retrieves, and removes statements.
 * Supports lookup by id, portfolio id, and generating user id.
 *
 * @explanation
 * Use this interface to implement data access for statements.
 * Persistence implementations map rows to `Statement` entities.
 *
 * @example
 * const STMT = await STATEMENT_REPO.findById(ID);
 *
 * @author Moisés Reis
 *
 * @date 2026-09-13
 */
export interface IStatement {
  /**
   * @summary
   * Retrieves the statement with the provided id.
   *
   * @remarks
   * Returns null when no statement matches.
   *
   * @explanation
   * Use this method to look up a single statement by its
   * unique identifier. Callers check null for existence.
   *
   * @param id - The unique identifier of the statement.
   *
   * @returns The entry or `null`.
   *
   * @example
   * const STMT = await STATEMENT_REPO.findById(ID);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-13
   */
  findById(id: EntityId): Promise<Statement | null>

  /**
   * @summary
   * Retrieves all statements of the provided portfolio.
   *
   * @remarks
   * Returns an empty array when no statements match.
   *
   * @explanation
   * Use this method to list statements linked to a
   * portfolio. Returns an empty array for no matches.
   *
   * @param portfolioId - The unique identifier of the portfolio.
   *
   * @returns The matching entries.
   *
   * @example
   * const STMTS = await STATEMENT_REPO
   *   .findAllByPortfolioId(PORTFOLIO_ID);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-13
   */
  findAllByPortfolioId(
    portfolioId: EntityId
  ): Promise<Statement[]>

  /**
   * @summary
   * Retrieves all statements of the provided portfolios.
   *
   * @remarks
   * Returns an empty array when no statements match.
   *
   * @explanation
   * Use this method to list statements linked to several
   * portfolios. Returns an empty array for no matches.
   *
   * @param portfolioIds - The identifiers of the portfolios.
   *
   * @returns The matching entries.
   *
   * @example
   * const STMTS = await STATEMENT_REPO
   *   .findAllByPortfolioIds(PORTFOLIO_IDS);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-15
   */
  findAllByPortfolioIds(
    portfolioIds: EntityId[]
  ): Promise<Statement[]>

  /**
   * @summary
   * Retrieves all statements generated by the provided user.
   *
   * @remarks
   * Returns an empty array when no statements match.
   *
   * @explanation
   * Use this method to list statements created by a
   * user. Returns an empty array for no matches.
   *
   * @param userId - The unique identifier of the user.
   *
   * @returns The matching entries.
   *
   * @example
   * const STMTS = await STATEMENT_REPO
   *   .findAllByGeneratedByUserId(USER_ID);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-13
   */
  findAllByGeneratedByUserId(
    userId: EntityId
  ): Promise<Statement[]>

  /**
   * @summary
   * Retrieves all statements generated by the provided users.
   *
   * @remarks
   * Returns an empty array when no statements match.
   *
   * @explanation
   * Use this method to list statements generated by
   * several users. Returns an empty array for no matches.
   *
   * @param userIds - The unique identifiers of the users.
   *
   * @returns The matching entries.
   *
   * @example
   * const STMTS = await STATEMENT_REPO
   *   .findAllByGeneratedByUserIds(USER_IDS);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-15
   */
  findAllByGeneratedByUserIds(
    userIds: EntityId[]
  ): Promise<Statement[]>

  /**
   * @summary
   * Persists the provided statement.
   *
   * @remarks
   * Inserts a new record when the statement has no id;
   * otherwise updates the existing record.
   *
   * @explanation
   * Use this method to create or update a statement.
   * The persisted entity with its id is returned.
   *
   * @param statement - The statement to persist.
   *
   * @returns The persisted entry.
   *
   * @example
   * const STMT = await STATEMENT_REPO.save(NEW_STMT);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-13
   */
  save(statement: Statement): Promise<Statement>

  /**
   * @summary
   * Removes the statement with the provided id.
   *
   * @remarks
   * Resolves when the statement is removed.
   *
   * @explanation
   * Use this method to delete a statement record.
   * The promise resolves once the operation completes.
   *
   * @param id - The unique identifier of the statement.
   *
   * @returns Resolves when removed.
   *
   * @example
   * await STATEMENT_REPO.delete(ID);
   *
   * @author Moisés Reis
   *
   * @date 2026-09-13
   */
  delete(id: EntityId): Promise<void>
}
