import { ID } from "@/__tests__/__fixtures__";
import { createInMemoryRepository } from "@/__tests__/__fixtures__/_in-memory-repository";
import { Statement as StatementEntity } from "@/business/entities/report/statement.entity";
import type { IStatement } from "@/business/interfaces/report/statement.interface";
import { EntityId } from "@/business/value-objects/entity-id.vo";

/**
 * Represents the default statement fixture.
 *
 * The fixture covers January 2026 for the default portfolio
 * and points to a synthetic PDF file URL.
 */
export const STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: new Date("2026-01-01T00:00:00.000Z"),
    periodEnd: new Date("2026-01-31T00:00:00.000Z"),
    fileUrl: "https://example.com/statements/fia-january.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.DEFAULT,
);

/**
 * Represents a secondary statement fixture.
 *
 * The fixture covers February 2026 for the other portfolio
 * and uses a different synthetic PDF file URL.
 */
export const OTHER_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.OTHER),
    periodStart: new Date("2026-02-01T00:00:00.000Z"),
    periodEnd: new Date("2026-02-28T00:00:00.000Z"),
    fileUrl: "https://example.com/statements/rf-february.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.OTHER,
);

/**
 * Represents a third statement fixture.
 *
 * The fixture covers March 2026 for the default portfolio.
 * It was generated by the other user for multi-user tests.
 */
export const THIRD_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: new Date("2026-03-01T00:00:00.000Z"),
    periodEnd: new Date("2026-03-31T00:00:00.000Z"),
    fileUrl: "https://example.com/statements/fia-march.pdf",
    generatedByUserId: EntityId.create(ID.USER.OTHER),
  },
  ID.STATEMENT.THIRD,
);

/**
 * Represents the default statement fixture after update.
 *
 * The fixture reuses the same period as {@link STATEMENT}
 * but points to an updated synthetic PDF file URL.
 */
export const UPDATED_STATEMENT = StatementEntity.create(
  {
    portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
    periodStart: STATEMENT.periodStart,
    periodEnd: STATEMENT.periodEnd,
    fileUrl: "https://example.com/statements/fia-january-v2.pdf",
    generatedByUserId: EntityId.create(ID.USER.DEFAULT),
  },
  ID.STATEMENT.DEFAULT,
);

/**
 * Represents a fresh statement fixture without a fixed ID.
 *
 * The fixture is useful for create-and-save tests where the
 * repository assigns the identifier. It covers April 2026.
 */
export const FRESH_STATEMENT = StatementEntity.create({
  portfolioId: EntityId.create(ID.PORTFOLIO.DEFAULT),
  periodStart: new Date("2026-04-01T00:00:00.000Z"),
  periodEnd: new Date("2026-04-30T00:00:00.000Z"),
  fileUrl: "https://example.com/statements/fia-april.pdf",
  generatedByUserId: EntityId.create(ID.USER.DEFAULT),
});

/** Represents the default statement identifier. */
export const STATEMENT_ID = ID.STATEMENT.DEFAULT;

/** Represents the other statement identifier. */
export const OTHER_STATEMENT_ID = ID.STATEMENT.OTHER;

/** Represents the third statement identifier. */
export const THIRD_STATEMENT_ID = ID.STATEMENT.THIRD;

/** Represents the default portfolio identifier. */
export const PORTFOLIO_ID = ID.PORTFOLIO.DEFAULT;

/** Represents the other portfolio identifier. */
export const OTHER_PORTFOLIO_ID = ID.PORTFOLIO.OTHER;

/** Represents the default user identifier. */
export const USER_ID = ID.USER.DEFAULT;

/** Represents the other user identifier. */
export const OTHER_USER_ID = ID.USER.OTHER;

/**
 * Represents the start date of the default statement period.
 *
 * The value is derived from {@link STATEMENT.periodStart}.
 */
export const PERIOD_START = STATEMENT.periodStart;

/**
 * Represents the end date of the default statement period.
 *
 * The value is derived from {@link STATEMENT.periodEnd}.
 */
export const PERIOD_END = STATEMENT.periodEnd;

/**
 * Creates an in-memory implementation of the
 * {@link IStatement} repository.
 *
 * The repository stores {@link StatementEntity} instances
 * in memory. It supports finding by ID, finding all by
 * portfolio ID, finding all by generated-by user ID,
 * saving, and deleting.
 *
 * @returns A fresh {@link IStatement} instance backed by
 *          an in-memory store.
 */
export function createInMemoryStatementRepository(): IStatement {
  const BASE = createInMemoryRepository<
    Awaited<ReturnType<IStatement["save"]>>
  >({ extractId: (s) => s.id });

  return {
    findById: (id) => BASE.findById(id),
    async findAllByPortfolioId(portfolioId) {
      return BASE.match((s) => s.portfolioId === portfolioId);
    },
    async findAllByGeneratedByUserId(userId) {
      return BASE.match((s) => s.generatedByUserId === userId);
    },
    save: (statement) => BASE.save(statement),
    delete: (id) => BASE.delete(id),
  };
}
