import { beforeEach, describe, expect, it } from "vitest";

import {
  createInMemoryStatementRepository,
  PERIOD_END,
  PERIOD_START,
  PORTFOLIO_ID,
  STATEMENT,
  STATEMENT_ID,
  USER_ID,
} from "@/__tests__/__helpers__/interfaces/_statement.test.helper";

import { Statement } from "@/business/entities/report/statement.entity";
import type { IStatement } from "@/business/interfaces/report/statement.interface";
import { EntityId } from "@/business/value-objects/entity-id.vo";

describe("IStatement", () => {
  let REPOSITORY: IStatement;

  beforeEach(() => {
    REPOSITORY = createInMemoryStatementRepository();
  });

  describe("findById", () => {
    it("returns the persisted statement", async () => {
      await REPOSITORY.save(STATEMENT);

      const FOUND = await REPOSITORY.findById(EntityId.create(STATEMENT_ID));

      expect(FOUND?.id).toBe(STATEMENT.id);
    });

    it("returns null when the statement does not exist", async () => {
      expect(
        await REPOSITORY.findById(EntityId.create(STATEMENT_ID)),
      ).toBeNull();
    });
  });

  describe("findAllByPortfolioId", () => {
    it("returns all persisted statements for the portfolio", async () => {
      const SECOND_STATEMENT = Statement.create(
        {
          portfolioId: EntityId.create(PORTFOLIO_ID),
          periodStart: new Date("2026-08-01T00:00:00.000Z"),
          periodEnd: new Date("2026-08-31T00:00:00.000Z"),
          fileUrl: "https://example.com/statements/august.pdf",
          generatedByUserId: EntityId.create(USER_ID),
        },
        "6a1f2c3d-9e8b-4a21-b3d7-1c7e9f0a4b52",
      );

      await REPOSITORY.save(STATEMENT);
      await REPOSITORY.save(SECOND_STATEMENT);

      const FOUND = await REPOSITORY.findAllByPortfolioId(
        EntityId.create(PORTFOLIO_ID),
      );

      expect(FOUND.length).toBe(2);
      expect(FOUND[0]?.id).toBe(STATEMENT.id);
      expect(FOUND[1]?.id).toBe(SECOND_STATEMENT.id);
    });

    it("returns an empty array when there are no matches", async () => {
      expect(
        await REPOSITORY.findAllByPortfolioId(EntityId.create(PORTFOLIO_ID)),
      ).toEqual([]);
    });
  });

  describe("findAllByGeneratedByUserId", () => {
    it("returns all persisted statements generated by the user", async () => {
      const SECOND_STATEMENT = Statement.create(
        {
          portfolioId: EntityId.create(PORTFOLIO_ID),
          periodStart: new Date("2026-08-01T00:00:00.000Z"),
          periodEnd: new Date("2026-08-31T00:00:00.000Z"),
          fileUrl: "https://example.com/statements/august.pdf",
          generatedByUserId: EntityId.create(USER_ID),
        },
        "6a1f2c3d-9e8b-4a21-b3d7-1c7e9f0a4b52",
      );

      await REPOSITORY.save(STATEMENT);
      await REPOSITORY.save(SECOND_STATEMENT);

      const FOUND = await REPOSITORY.findAllByGeneratedByUserId(
        EntityId.create(USER_ID),
      );

      expect(FOUND.length).toBe(2);
      expect(FOUND[0]?.id).toBe(STATEMENT.id);
      expect(FOUND[1]?.id).toBe(SECOND_STATEMENT.id);
    });

    it("returns an empty array when there are no matches", async () => {
      expect(
        await REPOSITORY.findAllByGeneratedByUserId(EntityId.create(USER_ID)),
      ).toEqual([]);
    });
  });

  describe("save", () => {
    it("persists a new statement", async () => {
      await REPOSITORY.save(STATEMENT);

      const FOUND = await REPOSITORY.findById(EntityId.create(STATEMENT_ID));

      expect(FOUND?.id).toBe(STATEMENT.id);
    });

    it("updates an existing statement", async () => {
      await REPOSITORY.save(STATEMENT);

      const UPDATED = Statement.create(
        {
          portfolioId: EntityId.create(PORTFOLIO_ID),
          periodStart: PERIOD_START,
          periodEnd: PERIOD_END,
          fileUrl: "https://example.com/statements/july-updated.pdf",
          generatedByUserId: EntityId.create(USER_ID),
        },
        STATEMENT_ID,
      );

      await REPOSITORY.save(UPDATED);

      const FOUND = await REPOSITORY.findById(EntityId.create(STATEMENT_ID));

      expect(FOUND?.fileUrl).toBe(
        "https://example.com/statements/july-updated.pdf",
      );
    });
  });

  describe("delete", () => {
    it("removes the persisted statement", async () => {
      await REPOSITORY.save(STATEMENT);

      await REPOSITORY.delete(EntityId.create(STATEMENT_ID));

      expect(
        await REPOSITORY.findById(EntityId.create(STATEMENT_ID)),
      ).toBeNull();
    });
  });
});
